spring:
  application:
    name: chacall

  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

---
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

---
# NoHandlerFoundException을 위한 옵션
spring:
  web:
    resources:
      add-mappings: false

---
server:
  port: 8080
  profile: local
  http-url: ${HTTP_URL}
  web-domain-urls:
    - "http://localhost:5173"
    - "https://chacall.co.kr"
    - "http://localhost:8080"

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 2592000000 # 30일

---
# S3 관련 설정
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      cloud-front-url: ${CLOUD_FRONT_URL}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---
app:
  pdf:
    font-path: classpath:fonts/NotoSansKR-Regular.ttf  # 한글 폰트(리소스에 포함)
    template: reservation-estimate # PDF 템플릿 파일명 (resources/templates/reservation-estimate.html)

---
spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration