spring:
  application:
    name: chacall

  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

---
# NoHandlerFoundException을 위한 옵션
spring:
  web:
    resources:
      add-mappings: false

---
server:
  port: 8000
  profile: dev
  http-url: ${HTTP_URL}
  web-domain-urls:
    - "http://localhost:5173"
    - "https://chacall.co.kr"
    - "http://localhost:8080"

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 2592000000 # 30일